service: lambda
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  image:
    handler: handler.image
    events:
      - http:
          path: /image
          method: get